### ISSUE TITLE
[Discussion] Answer on StackOverflow

### ISSUE THREAD

**Issue by giuliohome** [EldHasp/CyberForumMyCycleRepos#1]
Thank you for sharing [your answer there](https://stackoverflow.com/a/68376636/11323942).

I'll be able to award the bounty to you in 6 hours.

**Comment by giuliohome** [comment]
This is the part I'd like to discuss with you (but only here, I'm not happy with SO and the mods).

> This string is passed to the DependencyObject to be assigned to the Text property. BUT in the Text property there is a string "123.000". And since it is not equal to the string "123", the value "123" is assigned to the Text property - the point and zeros are gone!

Anyway you're not supposed to discuss this aspect with me, if you don't have further time. In that case feel free to close this issue. No worries.

> To solve the problem, you need to make a decision analyzing the current value of the Text property even before converting the number to a string. And if the same number can be obtained from Text, then the assignment should not occur.

My point of view is that the above should be the standard behavior when a binding is present.

> In order for the assignment not to occur, it is necessary to compare the new value not just with the current one, but convert both values ​​to the numeric type of the source property and compare these numbers. But DependencyObject doesn't "know" anything about bindings. Doesn't even know if this property has bindings.

Yes, unfortunately this is the current standard implementation, but I believe that the rationale behind is philosophically wrong. Logically, from a correct interpretation of the design pattern and the MVVM inspiring principles, I deem it should be the other way around.

**Comment by giuliohome** [comment]
IMHO it is a bug of the standard WPF control. In other words what you call the DependencyObject.

I think the real situation is that text property is string "123." and it is not equal to "123" but it should nonetheless keep "123." while the focus is in the control as part of the standard implementation. Otherwise Microsoft standpoint should be that a user is supposed to type a double as I described in my answer that a SO mod deleted.

For example it is possible to set `StringFormat={}{0:#,0.0}` in the standard Binding and one would expect that this could be a possible, easy fix, but the way the standard control is implemented is so ugly that it is really not usable even with a StringFormat due to how the cursor moves in the TextBox. 

You've written:
> The second, incidentally solved and often required, task is to restrict the user to enter "only numbers"

This task belongs to the view in the mvvm, it is responsibility of the control. In HTML there is `<input type="number">` , where is the equivalent in the WPF Textbox? Indeed there's something missing in the standard XAML control implementation.

I want to say that you deserve the bounty also for the style of your dialog and communication, in comparison to the arrogance of the mods and the other author (irrespective of the fact that xctk double control appears to be the practical solution). 

The way they overlooked and dismissed my answer is really idiotic (btw they downvoted and deleted my answer that makes sense from the standard WPF perspective and is a precedural solution in that regard, while they kept a very old but still upvoted "accepted" answer that is completely wrong ).

Thanks again for your analysis in conclusion.

**Comment by EldHasp** [comment]
Hello!

I'm not happy with StackOverflow moderation either. Especially the anonymous cons.
On our Forum (https://www.cyberforum.ru/wpf-silverlight/) minus are rarely used.
Only in the case of clearly negative content: spam, advertising, insults, etc.
The reputation of a question or answer only counts the pros.
Negative reviews are not displayed and necessarily require a reason for such a review.
StackOverflow has a lot of unreasonable cons, deletions, edits that change the meaning of a question or answer.
But, unfortunately, there is nothing we can do about it.

As for the question itself, as I wrote earlier, its reasons lie deep in the logic of DependecyObject and how bindings work with it.
Initially, it is a generic type that is not bound to a View.
At least, this is the type the authors tried to make.
But in fact, this is pointless, since, except for WPF UI elements, it is practically not used anywhere.
Due to its inherent universality, in general (for all possible use cases), it is impossible to make decisions when it is necessary to compare the target property directly with the source, and when, before comparing, the value of the target property must first be converted to the source type.

At the same time, the authors themselves broke their own abstraction by introducing additional parameters into the Binding type that are needed only when used in the GUI.
They could also add behavior changes for text UI elements, since this is the most commonly used WPF element.
But for some reason, they didn't.

It is quite easy to introduce the required behavior for UI elements and their bindings in source codes.
It will take at most several tens of lines.
But all the required members for a simple change are implemented as Private, Internal, Sealed.
Because of this, you have to do all this with the use of «Voodoo Magic».
And the code grows to almost a thousand lines.

I'm an amateur myself - not a professional programmer.
But I am interested in dealing with such complex problems.
I have written such detailed explanations on other questions on StackOverflow several times.
But almost always, they are either minus or deleted, often changes are made that make these articles meaningless.
But I hope they will help at least someone.

If you need a platform for some broad, global questions, you can post your question at https://www.cyberforum.ru/wpf-silverlight/.
This is the largest Russian-language resource, but English is also a valid language on it.

I wish you success!

**Comment by giuliohome** [comment]
Thank you a lot for your kindness! Much appreciated!
